#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 09, 2018 06:30:20 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GuiTest_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    GuiTest_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    GuiTest_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("741x509+346+152")
        top.title("New Toplevel")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.01, relwidth=0.17)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#296c5e")
        self.Frame1.configure(width=125)

        self.AddUser = Button(self.Frame1)
        self.AddUser.place(relx=0.0, rely=0.06, height=26, width=123)
        self.AddUser.configure(activebackground="#d9d9d9")
        self.AddUser.configure(text='''Agregar Usuario''')

        self.Train = Button(self.Frame1)
        self.Train.place(relx=0.16, rely=0.17, height=26, width=79)
        self.Train.configure(activebackground="#d9d9d9")
        self.Train.configure(text='''Entrenar''')

        self.RecognizerB = Button(self.Frame1)
        self.RecognizerB.place(relx=0.08, rely=0.29, height=26, width=89)
        self.RecognizerB.configure(activebackground="#d9d9d9")
        self.RecognizerB.configure(text='''Reconocer''')

        self.Quit = Button(self.Frame1)
        self.Quit.place(relx=0.32, rely=0.56, height=26, width=52)
        self.Quit.configure(activebackground="#d9d9d9")
        self.Quit.configure(text='''Salir''')

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.18, rely=-0.02, relheight=0.93, relwidth=0.84)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#00d9d9")
        self.Frame2.configure(width=625)

        self.Image = Label(self.Frame2)
        self.Image.place(relx=0.05, rely=0.08, height=398, width=574)
        self.Image.configure(width=574)

        self.Message = Label(top)
        self.Message.place(relx=0.55, rely=0.94, height=18, width=4)






if __name__ == '__main__':
    vp_start_gui()



